### ISSUE TITLE
internal server error 500

### ISSUE THREAD

**Issue by goldleewtje** [wienkit/prestashop-bolplaza#5]
After my boss updated both presta and php to the newest version whenever I try to access bol.com orders i get a blank screen with internal server error 500. Can you please help?

**Comment by mwienk** [comment]
A 500 error means you need to check your logs. I have just created a release for 1.4.2, you can download it at https://github.com/wienkit/prestashop-bolplaza/releases/download/1.4.2/bolplaza.zip. That release contains the dependencies as well (so you don't need composer anymore). That might fix your problem.

**Comment by goldleewtje** [comment]
much thanks that fixed it
